### ISSUE TITLE
Image uploading for problem statement not working

### ISSUE THREAD

**Issue by Dristy03** [RafikFarhad/SUST-Online-Judge#100]
There is an option of uploading image by providing media link. But whatever link is used, it always gives an error -'The link is not supported'.

**Comment by RafikFarhad** [comment]
Hey @Dristy03, 
We are investigating the issue. We will update about the fix as soon as possible. 
And thanks for reporting the issue.

**Comment by RafikFarhad** [comment]
@Dristy03 the issue has been resolved in the Judge panel. 
NB: You have to provide image URL not the image contained web page. The easiest to way to get the image link is to right click on the image and select "Copy Image Address" from your browser. 
Thanks again.

**Comment by Dristy03** [comment]
@RafikFarhad bhai, thank you . It's working.

**Comment by RafikFarhad** [comment]
Solved.
