### ISSUE TITLE
Subdomain Got Public Access

### ISSUE THREAD

**Issue by kcnaiamh** [RafikFarhad/SUST-Online-Judge#102]
I assume this is accidentally got public.
https://live.sustcseoj.com/
![image](https://user-images.githubusercontent.com/52814980/112022006-11fd5800-8b5c-11eb-9385-23c2692f81b6.png)

**Comment by RafikFarhad** [comment]
Hello @NaimulIslam9m , thanks for your concern. 
But this is the service that handles many of our feature like real time verdict update, dispatch emails and many more. To achieve the web socket connectivity. As it serves web socket, this is made public. 
Thanks.
