### ISSUE TITLE
Binary Size 

### ISSUE THREAD

**Issue by talatmursalin** [RafikFarhad/SUST-Online-Judge#13]
The max binary size has been limited to 64 Kb. Is there any chance it might cross the limit?

**Comment by RafikFarhad** [comment]
Do we have that now? @talatmursalin

**Comment by talatmursalin** [comment]
There has been no issue found related to this limit till now. Its safe to assume that 64 kb is safe limit for a binary.

**Comment by RafikFarhad** [comment]
Hope that, in docker installation it wont't be a problem. Closing.
