### ISSUE TITLE
Special Judge

### ISSUE THREAD

**Issue by RafikFarhad** [RafikFarhad/SUST-Online-Judge#14]
We need to find a way to pass the files to the validator code.
Also the steps for the special judge.

**Comment by RafikFarhad** [comment]
Possible Work Flow:
For each test case:

1. Run the user submission and store the user output stream to a file in {output_path}/{contest_id}/{submission_id}/{test_case}/user_output.txt
2. compile the validator
3. make a temporary folder in ~/temporary_data/{process_unique_id}/{problem_id}, lets refer it as #path_temporary (It can be skipped including step 9! )
4. copy the judge input for current test case at #path_temporary as judge_input.txt
5. copy the judge output for current test case at #path_temporary as judge_output.txt
6. copy the user output for current test case at #path_temporary as user_input.txt (we will found it form step 1)
7. Run the compiled validator binary with extra one parameter in the binrary.execute() function call.
8. If step 7 output "OK" then the answer is AC, otherwise WA. (We can make some upgrade by tweaking this.)
9. Delete the #path_temporary directory


NB: 
1. We will keep the step 1 file for other purposes like judge can view the difference or download it

@nilasrum  Please review this.

**Comment by RafikFarhad** [comment]
Necessary query to find Special Judge Info:

Replace this with problem fetching query.
` SELECT problems.*, special_sources.path as sp_path, special_sources.language as sp_language, special_sources.memory_limit as sp_memory_limit, special_sources.time_limit as sp_time_limit FROM `problems` JOIN special_sources on special_sources.problem_id = problems.id where problems.id=1 ;`

**Comment by talatmursalin** [comment]
implemented.
