### ISSUE TITLE
Skipped subSubmissions should be pushed 

### ISSUE THREAD

**Issue by RafikFarhad** [RafikFarhad/SUST-Online-Judge#53]
Skipped subSubmissions should be pushed to the database. Need discussion.

**Comment by RafikFarhad** [comment]
This is important, otherwise on a freeze submission, others can see only passed, so they can guess if that submission is AC or not.
Previously we discussed that this task would be handled by in web end, and `judge end` is already doing that, but there may occur a performance issue, whenever a sub-submissions view is occur, I have to do an extra query in `tescases` table, but if you populate those skipped cases in `sub_submissions`, this could be ignored.

If we are concern about `sub_submissions` table size, then we can clear the `skipped` testcase after the contest ends. And we can remove all sub-submissions

**Comment by RafikFarhad** [comment]
It is needed ASAP. @talatmursalin

**Comment by talatmursalin** [comment]
resolved (commit a7158838ec79b948d40f223697d60936f414cf2a).
