### ISSUE TITLE
Rank List issues

### ISSUE THREAD

**Issue by RafikFarhad** [RafikFarhad/SUST-Online-Judge#54]
- [ ] Problem stats not created if there is no entry for a problem
- [x] mark and public mark negative appears
- [x] public_accepted in rank_lists increments even if the contest is in freeze mode
- [x] public_penalty in rank_lists increments even if the contest is in freeze mode
- [x] one time I deleted all ranklist and subranklist entry from database and then rejudge one problem, the total_accepted incremented to 2, problem_stats was not clear

**Comment by talatmursalin** [comment]
fixed (judgeMod commit: 598caf3)
