### ISSUE TITLE
Problem Statement Page is Broken

### ISSUE THREAD

**Issue by kcnaiamh** [RafikFarhad/SUST-Online-Judge#99]
After updating 2/3 times the problem statement the page got broken
Here is the broken page:

![image](https://user-images.githubusercontent.com/52814980/110668948-0cb41b00-81f6-11eb-8c8a-30318d2a9da9.png)

The page should be look like this:

![image](https://user-images.githubusercontent.com/52814980/110669454-8d731700-81f6-11eb-9d72-3e47413b3f33.png)

**Comment by RafikFarhad** [comment]
Thanks @NaimulIslam9m for the issue.
The issue has been solved. Now you can check the statement page of your problem.
